# 这个是dfine的整个训练的配置，包括
# 1. 任务
# 2. 模型
# 3. 标准（比如损失，指标）
# 4. 后处理（模型推理后，过滤低置信度的框，将模型输出整理成适合任务的形式
# 5. 数据
# 6. 训练流程（轮数，学习率，优化器）
task: detection

model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor

use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 4    # save freq

DEIM: # 模型
  backbone: HGNetv2
  encoder: HybridEncoder
  decoder: DFINETransformer

# Add, default for step lr scheduler 
lrsheduler: flatcosine # 学习率
lr_gamma: 1
warmup_iter: 500 # 学习率热身
flat_epoch: 4000000
no_aug_epoch: 0

HGNetv2: # 主干模型
  pretrained: False
  local_model_dir: ./weight/hgnetv2/

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'

  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'


DFINETransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  eval_idx: -1
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  # NEW
  reg_max: 32
  reg_scale: 4

  # Auxiliary decoder layers dimension scaling
  # "eg. If num_layers: 6 eval_idx: -4,
  # then layer 3, 4, 5 are auxiliary decoder layers."
  layer_scale: 1  # 2


  num_points: [3, 6, 3] # [4, 4, 4] [3, 6, 3]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic

  dim_feedforward: 1024

PostProcessor:
  num_top_queries: 300 # 只取前300个框


DEIMCriterion: # 损失，匹配器
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5}
  losses: ['vfl', 'boxes', 'local']
  alpha: 0.75
  gamma: 2.0
  reg_max: 32

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0